services:
  App\ErrorBundle\EventListener\ExceptionListener:
    arguments:
      $client: '@guzzle.client'
      $webhookUrl: '%env(WEBHOOK_URL)%'
      $name: '%env(APP_NAME)%'
      $url: '%env(ERROR_URL)%'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  guzzle.client:
    class: GuzzleHttp\Client
    arguments: []