services:
  App\ErrorBundle\Service\ExceptionListener:
    arguments:
      $client: '@http_client' # Ajusta esto según tu cliente HTTP preferido
      $webhookUrl: '%app_error.webhook_url%'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

