services:
  App\ErrorBundle\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    arguments:
      $webhookUrl: '%env(DISCORD_WEBHOOK_URL)%'